<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Android投屏助手</AssemblyName>
    <RootNamespace>Android投屏助手</RootNamespace>
    <Platforms>AnyCPU</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ScrcpyFiles Include="..\scrcpy\**\*" />
    <Content Include="@(ScrcpyFiles)" LinkBase="scrcpy" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
